spring:
  datasource:
    url: jdbc:mysql://localhost:13306/usercenter?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8086
logging:
  level:
    com.zy: debug